### ISSUE TITLE
query could be a Dict rather than Vector{Pair}

### ISSUE THREAD

**Issue by rafaqz** [EcoJulia/GBIF.jl#47]
It's hard to change a query after `occurrences`. It would make sense to be able to update e.g. "limit" easily.

**Comment by tpoisot** [comment]
This one is by design - it's not a good idea to update the query parameters when the query has started. It becomes too easy to change *e.g.* the species name or bounding box, for example.

The other argument is that if there are a lot of records, a solution like `read!` will take a lot of time. I would rather keep the `while` with checkpointing, or encourage users to use a progressbar, etc. We used to have a function to get all occurrences, and it ended up *not* being user-friendly (for the users we tested it with).

**Comment by rafaqz** [comment]
Isn't this an internal implementation detail? I meant just to make it easier to update the object from within the package.
